### ISSUE TITLE
"More Info" dialog issues

### ISSUE THREAD

**Issue by imjustafox** [safewords/lewd-issues#1]
Modal Dialog spawned from "Info" button on the "Include a Topic" box is a struggle to keep open, Maybe turn this into a modal style where when clicked on it appears and then dissapears when clicked anywhere else on "dead page" 
Also: Learn more button just takes you to top of feed.

Will attach gif when i'm not on plane.

**Comment by WaffleThief123** [comment]
![Uploading infomodal.gif…]()

**Comment by imjustafox** [comment]
![infomodal](https://github.com/Safewords/lewd-issues/assets/26676249/696fe880-7273-42a7-8d1c-438a20e59304)

**Comment by corsair** [comment]
<img width="541" alt="Screenshot 2024-01-05 at 2 06 08 AM" src="https://github.com/Safewords/lewd-issues/assets/1847891/8eb144bc-5366-4b3c-b02c-991b07ee8033">

This has been resolved in [d245b8c](https://github.com/Safewords/lewd.net/commit/d245b8c3bb4917bf236619f17a7da582406de88b) by incorporating a proper modal with an expanded explanation.
