### ISSUE TITLE
New Login Notification Email Issues

### ISSUE THREAD

**Issue by imjustafox** [safewords/lewd-issues#2]
New Login notifications via email

Currently provided as a JSON blob which is not UX friendly.
Name/Handle/Etc is missing from greeting line 
```
Dear , 
```
instead of 
```
Dear Cyra
```

<img width="711" alt="image" src="https://github.com/Safewords/lewd-issues/assets/26676249/40da2f7a-4e39-4bb6-8305-17a792f7c5a9">

**Comment by corsair** [comment]
<img width="1122" alt="image" src="https://github.com/Safewords/lewd-issues/assets/1847891/0fa3728e-6843-44fb-9529-45f581a25368">

The email layout has been redesigned to improve UX and includes better communication about email notifications.

Resolved in [26391b7](https://github.com/Safewords/lewd.net/commit/26391b7d3f3d2cfcbbf23ccef9a19a0a68f6ade7).
