### ISSUE TITLE
Copyright Year Incorrect

### ISSUE THREAD

**Issue by imjustafox** [safewords/lewd-issues#3]
Right Column Footer states "Copyright 2023" when it's 2024. 

<img width="379" alt="image" src="https://github.com/Safewords/lewd-issues/assets/26676249/e7bc355a-8d0c-462a-b656-eadbe81bcd0d">

**Comment by corsair** [comment]
Resolved in [39743a9](https://github.com/Safewords/lewd.net/commit/39743a99037a89aa085c1a2a7a04bd8eda48a32c).
