### ISSUE TITLE
"Command Column" loses items when going from tablet landscape to mobile.

### ISSUE THREAD

**Issue by imjustafox** [safewords/lewd-issues#4]
"Command Column" (or menu column) loses subscription button when going from expanded to tablet compressed. 

![command-column](https://github.com/Safewords/lewd-issues/assets/26676249/dc96fef7-3dcf-4a3e-bebc-947f266b9c7c)

**Comment by corsair** [comment]
Resolved in [0dfb57d](https://github.com/Safewords/lewd.net/commit/0dfb57d2653b80d2973459274c885ee48ad89ac1).

Thanks for this report, @WaffleThief123!
